#include "continuous/scene/Components.h"

CN_REFLECT_BEGIN(::cn::scene::NameComponent)
    CN_REFLECT_FIELD(name, String)
CN_REFLECT_END(::cn::scene::NameComponent)

CN_REFLECT_BEGIN(::cn::scene::TransformComponent)
    CN_REFLECT_FIELD_STRUCT(local, ::cn::math::Transform)
CN_REFLECT_END(::cn::scene::TransformComponent)

CN_REFLECT_BEGIN(::cn::scene::CameraComponent)
    CN_REFLECT_FIELD_RANGE(fov_y_deg, F32, 1.0f, 170.0f, 0.1f)
    CN_REFLECT_FIELD_RANGE(near_z,    F32, 0.001f, 100.0f, 0.001f)
    CN_REFLECT_FIELD_RANGE(far_z,     F32, 1.0f,   100000.0f, 1.0f)
    CN_REFLECT_FIELD_COLOR(clear_color)
    CN_REFLECT_FIELD(primary, Bool)
CN_REFLECT_END(::cn::scene::CameraComponent)

CN_REFLECT_ENUM_BEGIN(::cn::scene::LightType)
    CN_REFLECT_ENUM_VALUE(Directional)
    CN_REFLECT_ENUM_VALUE(Point)
    CN_REFLECT_ENUM_VALUE(Spot)
CN_REFLECT_ENUM_END(::cn::scene::LightType)

CN_REFLECT_BEGIN(::cn::scene::LightComponent)
    CN_REFLECT_FIELD_STRUCT(type, ::cn::scene::LightType)
    CN_REFLECT_FIELD_COLOR(color)
    CN_REFLECT_FIELD_RANGE(intensity, F32, 0.0f, 50.0f, 0.05f)
    CN_REFLECT_FIELD_RANGE(range,     F32, 0.0f, 1000.0f, 0.1f)
    CN_REFLECT_FIELD_RANGE(spot_inner_deg, F32, 0.0f, 180.0f, 0.1f)
    CN_REFLECT_FIELD_RANGE(spot_outer_deg, F32, 0.0f, 180.0f, 0.1f)
    CN_REFLECT_FIELD(casts_shadow, Bool)
CN_REFLECT_END(::cn::scene::LightComponent)

CN_REFLECT_BEGIN(::cn::scene::MeshRenderer)
    CN_REFLECT_FIELD(mesh_id, String)
    CN_REFLECT_FIELD(cast_shadow, Bool)
    CN_REFLECT_FIELD(visible, Bool)
CN_REFLECT_END(::cn::scene::MeshRenderer)

CN_REFLECT_ENUM_BEGIN(::cn::scene::ColliderShape)
    CN_REFLECT_ENUM_VALUE(Box)
    CN_REFLECT_ENUM_VALUE(Sphere)
    CN_REFLECT_ENUM_VALUE(Capsule)
CN_REFLECT_ENUM_END(::cn::scene::ColliderShape)

CN_REFLECT_BEGIN(::cn::scene::RigidBodyComponent)
    CN_REFLECT_FIELD_STRUCT(shape, ::cn::scene::ColliderShape)
    CN_REFLECT_FIELD(size, Vec3)
    CN_REFLECT_FIELD_RANGE(mass,        F32, 0.0f, 10000.0f, 0.1f)
    CN_REFLECT_FIELD_RANGE(friction,    F32, 0.0f, 5.0f, 0.01f)
    CN_REFLECT_FIELD_RANGE(restitution, F32, 0.0f, 1.0f, 0.01f)
    CN_REFLECT_FIELD(is_static, Bool)
    CN_REFLECT_FIELD(is_trigger, Bool)
CN_REFLECT_END(::cn::scene::RigidBodyComponent)

CN_REFLECT_BEGIN(::cn::scene::CharacterControllerComponent)
    CN_REFLECT_FIELD_RANGE(height,           F32, 0.1f, 4.0f,   0.01f)
    CN_REFLECT_FIELD_RANGE(radius,           F32, 0.05f, 2.0f,  0.01f)
    CN_REFLECT_FIELD_RANGE(step_height,      F32, 0.0f, 1.0f,   0.01f)
    CN_REFLECT_FIELD_RANGE(max_walk_slope_deg,F32, 0.0f, 89.0f, 0.5f)
    CN_REFLECT_FIELD_RANGE(move_speed,       F32, 0.0f, 50.0f,  0.1f)
    CN_REFLECT_FIELD_RANGE(jump_speed,       F32, 0.0f, 30.0f,  0.1f)
CN_REFLECT_END(::cn::scene::CharacterControllerComponent)

CN_REFLECT_BEGIN(::cn::scene::AudioSourceComponent)
    CN_REFLECT_FIELD(clip_id, String)
    CN_REFLECT_FIELD_RANGE(volume, F32, 0.0f, 2.0f, 0.01f)
    CN_REFLECT_FIELD_RANGE(pitch,  F32, 0.05f, 4.0f, 0.01f)
    CN_REFLECT_FIELD(loop, Bool)
    CN_REFLECT_FIELD(play_on_start, Bool)
    CN_REFLECT_FIELD(spatialize, Bool)
    CN_REFLECT_FIELD_RANGE(min_distance, F32, 0.0f, 100.0f, 0.1f)
    CN_REFLECT_FIELD_RANGE(max_distance, F32, 0.0f, 1000.0f, 0.1f)
CN_REFLECT_END(::cn::scene::AudioSourceComponent)

CN_REFLECT_BEGIN(::cn::scene::AudioListenerComponent)
    CN_REFLECT_FIELD(primary, Bool)
CN_REFLECT_END(::cn::scene::AudioListenerComponent)

CN_REFLECT_ENUM_BEGIN(::cn::scene::NetRole)
    CN_REFLECT_ENUM_VALUE(None)
    CN_REFLECT_ENUM_VALUE(Authority)
    CN_REFLECT_ENUM_VALUE(Replicated)
CN_REFLECT_ENUM_END(::cn::scene::NetRole)

CN_REFLECT_BEGIN(::cn::scene::NetReplicateComponent)
    CN_REFLECT_FIELD_STRUCT(role, ::cn::scene::NetRole)
    CN_REFLECT_FIELD(net_id, U32)
    CN_REFLECT_FIELD_RANGE(send_interval, F32, 0.001f, 1.0f, 0.001f)
    CN_REFLECT_FIELD(interpolate, Bool)
CN_REFLECT_END(::cn::scene::NetReplicateComponent)

CN_REFLECT_BEGIN(::cn::scene::ScriptComponent)
    CN_REFLECT_FIELD(class_name, String)
CN_REFLECT_END(::cn::scene::ScriptComponent)
